### ISSUE TITLE
`fno:type` is not defined, and inconsistently used

### ISSUE THREAD

**Issue by pchampin** [FnOio/fnoio.github.io#1]
(not sure if this is the right place for giving feedback on https://fno.io/spec/, version from 2019-05-29?)

In examples [4](https://fno.io/spec/#fn-parameter), [6](https://fno.io/spec/#fn-output), [8](https://fno.io/spec/#h-complete-example) and [15](https://fno.io/spec/#h-full-example), a property `fno:type` is used. However, 

* this property is not defined by the spec;
* it is used inconsistently: in examples 4, 6 and 8, it is applied to the predicates linked to parameters; in example 15, it is applied directly to the parameters;
* in examples 4, 6 and 8, it seems to duplicate the semantics of `rdfs:range`.

**Comment by bjdmeest** [comment]
You are right! In fact, I extracted the spec from this repo and put it in a [dedicated repo](https://github.com/FnOio/fno-specification) to better track these kinds of issues.
I also updated the spec to fix your actual comment: indeed fno:type should be applied directly to the parameter (https://fno.io/spec/#fn-parameter)
